export const GET_USAGE_FORMULA_REQUEST = "GET_USAGE_FORMULA_REQUEST";
export const GET_USAGE_FORMULA_SUCCESS = "GET_USAGE_FORMULA__SUCCESS";
export const GET_USAGE_FORMULA_ERROR = "GET_USAGE_FORMULA__ERROR";

export const ADD_USAGE_FORMULA_REQUEST = "GET_USAGE_FORMULA_REQUEST";
export const ADD_USAGE_FORMULA_SUCCESS = "GET_USAGE_FORMULA__SUCCESS";
export const ADD_USAGE_FORMULA_ERROR = "GET_USAGE_FORMULA__ERROR";
