export const ADD_PRESSCRIPTION_REQUEST = 'ADD_PRESSCRIPTION_REQUEST';
export const  ADD_PRESSCRIPTION_SUCCESS = 'ADD_PRESSCRIPTION_SUCCESS';
export const  ADD_PRESSCRIPTION_ERROR = ' ADD_PRESSCRIPTION_ERROR';

