export const GET_SINGLE_PRESCRIPTION_REQUEST = 'GET_SINGLE_PRESCRIPTION_REQUEST';
export const  GET_SINGLE_PRESCRIPTION_SUCCESS = 'GET_SINGLE_PRESCRIPTION_SUCCESS';
export const  GET_SINGLE_PRESCRIPTION_ERROR = ' GET_SINGLE_PRESCRIPTION_ERROR';

export const GET_PRESCRIPTIONS_REQUEST = 'GET_PRESCRIPTIONS_REQUEST';
export const  GET_PRESCRIPTIONS_SUCCESS = 'GET_PRESCRIPTIONS_SUCCESS';
export const  GET_PRESCRIPTIONS_ERROR =  'GET_PRESCRIPTIONS_ERROR';

