export const ADD_PRESCRIPTION_REQUEST = 'ADD_PRESCRIPTION_REQUEST';
export const  ADD_PRESCRIPTION_SUCCESS = 'ADD_PRESCRIPTION_SUCCESS';
export const  ADD_PRESCRIPTION_ERROR = ' ADD_PRESCRIPTION_ERROR';

export const GET_PRESCRIPTIONS_REQUEST = 'GET_PRESCRIPTIONS_REQUEST';
export const  GET_PRESCRIPTIONS_SUCCESS = 'GET_PRESCRIPTIONS_SUCCESS';
export const  GET_PRESCRIPTIONS_ERROR =  'GET_PRESCRIPTIONS_ERROR';

