export const GET_USAGE_FORMULA_REQUEST = 'GET_USAGE_FORMULA_REQUEST';
export const GET_USAGE_FORMULA__SUCCESS = 'GET_USAGE_FORMULA__SUCCESS';
export const GET_USAGE_FORMULA__ERROR =  'GET_USAGE_FORMULA__ERROR';
